import { type NextPage } from "next";
import Head from "next/head";
import { IQr, useAuth } from "@/contexts/AuthContext";
import { useQuery } from "@tanstack/react-query";
import { http } from "@/utils/http";
import { setAuthCredentials } from "@/utils/auth-utils";
import { useEffect } from "react";

const Home: NextPage = () => {
  const { getToken, setCreds, resetSession, user, number } = useAuth();
  const { data: qrData } = useQuery<IQr>({
    queryKey: ["session"],
    queryFn: async () => {
      const res = await http.post("/api/NERDWHATS_AMERICA/start-session");
      if (res.data.status === "CONNECTED") {
        setCreds();
      } else {
        resetSession();
      }
      return res.data;
    },
    refetchOnWindowFocus: "always",
    refetchInterval: 3000,
  });  

  useEffect(() => {
    getToken()
  }, [user, qrData?.status])
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 text-white">
          <h1 className="text-5xl">Scan With Whatsapp</h1>
          {qrData?.qrcode && qrData?.status != "CONNECTED" && (
            <img src={qrData.qrcode} alt="qr" />
          )}
          {qrData?.status === "CONNECTED" && (
            <>
              <h1 className="text-6xl text-white">CONNECTED</h1>
              <p>Welcome {user}</p>
              <p>Your number is {number}</p>
            </>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
